// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clipboard} from '../models';

export function GetClipboardHistory():Promise<Array<clipboard.StringData>>;
